name: Production deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.POLDPLAST_HOSTNAME }}
          username: ${{ secrets.POLDPLAST_USERNAME }}
          port: ${{ secrets.POLDPLAST_PORT }}
          key: ${{ secrets.POLDPLAST_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.POLDPLAST_HOME }}
            git fetch 
            git reset ${{ github.sha }} --hard
            php83 composer.phar install --no-dev

    concurrency:
      group: master
      cancel-in-progress: true
