name: Tests

on:
  push:
    branches:
      - '**'

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/composer
          key: php${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: php${{ matrix.php-version }}-composer-

      - name: Install dependencies
        run: composer install --no-progress

      - name: Run tests
        run: ./vendor/bin/phpunit --no-coverage test
